
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'az' | 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Translations object
const translations = {
  az: {
    // Common
    'common.discount': 'ENDİRİM',
    'common.viewDetails': 'Ətraflı bax',
    'common.viewAll': 'Hamısına bax',
    'common.search': 'Axtar...',
    'common.loadMore': 'Daha çox',
    'common.noData': 'Məlumat tapılmadı',
    
    // Home
    'home.demoLogin': 'Demo rejimdə test istifadəçiləri ilə giriş edə bilərsiniz',
    'home.viewDetails': 'Ətraflı bax',
    'home.viewAllProducts': 'Bütün məhsullara bax',
    'home.viewAllServices': 'Bütün xidmətlərə bax',
    
    // Services
    'services.title': 'Xidmətlərimiz',
    'services.description': 'Peşəkar komandamızla keyfiyyətli gözəllik xidmətləri',
    'services.search': 'Xidmətləri axtar...',
    'services.duration': 'Müddət',
    'services.minutes': 'dəqiqə',
    'services.benefits': 'Faydalar',
    'services.viewDetails': 'Ətraflı bax',
    'services.loadMore': 'Daha çox',
    'services.cta': 'Rezervasiya et',
    'services.bookNow': 'İndi rezerv et',
    'services.noDescription': 'Təsvir mövcud deyil',
    'services.noServicesAdded': 'Hələ heç bir xidmət əlavə edilməyib',
    'services.viewServicesPage': 'Xidmətlər səhifəsinə bax',
    'services.viewAllServices': 'Bütün xidmətlərə bax',
    
    // Service Detail
    'service.backToServices': 'Xidmətlərə qayıt',
    'service.minutes': 'dəqiqə',
    'service.benefits': 'Faydalar',
    'service.bookNow': 'İndi rezerv et',
    'service.recommendedProducts': 'Tövsiyə olunan məhsullar',
    'service.viewProductDetails': 'Məhsul detallarına bax',
    
    // Products
    'products.title': 'Məhsullarımız',
    'products.description': 'Keyfiyyətli gözəllik məhsulları',
    'products.search': 'Məhsulları axtar...',
    'products.cta': 'Sifariş ver',
    'products.viewDetails': 'Ətraflı bax',
    'products.bookNow': 'Sifariş ver',
    'products.noDescription': 'Təsvir mövcud deyil',
    'products.noProductsAdded': 'Hələ heç bir məhsul əlavə edilməyib',
    'products.viewProductsPage': 'Məhsullar səhifəsinə bax',
    
    // Product Detail
    'product.backToProducts': 'Məhsullara qayıt',
    'product.details': 'Detallar',
    'product.howToUse': 'İstifadə qaydası',
    'product.ingredients': 'Tərkib',
    'product.bookAppointment': 'Təyinat rezerv et',
    'product.relatedServices': 'Əlaqəli xidmətlər',
    'product.viewServiceDetails': 'Xidmət detallarına bax',
    
    // Contact
    'contact.name': 'Ad',
    'contact.namePlaceholder': 'Adınızı daxil edin',
    'contact.email': 'E-poçt',
    'contact.emailPlaceholder': 'E-poçt ünvanınızı daxil edin',
    'contact.phone': 'Telefon',
    'contact.phonePlaceholder': 'Telefon nömrənizi daxil edin',
    'contact.subject': 'Mövzu',
    'contact.subjectPlaceholder': 'Mövzunu daxil edin',
    'contact.message': 'Mesaj',
    'contact.messagePlaceholder': 'Mesajınızı daxil edin',
    'contact.send': 'Göndər',
    'contact.address': 'Ünvan',
    'contact.phoneNumber': 'Telefon nömrəsi',
    'contact.emailAddress': 'E-poçt ünvanı',
    'contact.workingHours': 'İş saatları',
    
    // Booking
    'booking.title': 'Təyinat Rezervasiyası',
    'booking.customerInfo': 'Müştəri məlumatları',
    'booking.services': 'Xidmətlər',
    'booking.products': 'Məhsullar',
    'booking.payment': 'Ödəniş',
    'booking.confirmation': 'Təsdiq',
    'booking.gender': 'Cins',
    'booking.male': 'Kişi',
    'booking.female': 'Qadın',
    'booking.fullName': 'Tam ad',
    'booking.fullNamePlaceholder': 'Məsələn: Əli Məmmədov',
    'booking.fullNameValidation': 'Tam ad 10-100 simvol arasında olmalıdır',
    'booking.genderRequired': 'Cins seçilməlidir',
    'booking.email': 'E-poçt',
    'booking.emailPlaceholder': 'məsələn@example.com',
    'booking.emailValidation': 'Düzgün e-poçt ünvanı daxil edin',
    'booking.phone': 'Telefon',
    'booking.phonePlaceholder': '+994 XX XXX XX XX',
    'booking.phoneRequired': 'Telefon nömrəsi tələb olunur',
    'booking.notes': 'Qeydlər',
    'booking.notesPlaceholder': 'Əlavə qeydlərinizi daxil edin',
    'booking.date': 'Tarix',
    'booking.dateRequired': 'Tarix seçilməlidir',
    'booking.time': 'Vaxt',
    'booking.timeRequired': 'Vaxt seçilməlidir',
    'booking.availableForNextDays': 'Növbəti',
    'booking.days': 'gün ərzində mövcuddur',
    'booking.workingHours': 'İş saatları',
    'booking.next': 'Növbəti',
    'booking.previous': 'Əvvəlki',
    'booking.searchServices': 'Xidmətləri axtar...',
    'booking.minutes': 'dəqiqə',
    'booking.moreInfo': 'Ətraflı məlumat',
    'booking.noDescription': 'Təsvir mövcud deyil',
    'booking.selectStaff': 'İşçi seçin',
    'booking.chooseStaff': 'İşçi seçin',
    'booking.noServices': 'Xidmət tapılmadı',
    'booking.selectedServices': 'Seçilmiş xidmətlər',
    'booking.servicesTotal': 'Xidmətlər cəmi',
    'booking.totalDuration': 'Ümumi müddət',
    'booking.duration': 'Müddət',
    'booking.endTime': 'Bitmə vaxtı',
    'booking.servicesRequired': 'Ən azı bir xidmət seçilməlidir',
    'booking.staffRequired': 'Bütün xidmətlər üçün işçi seçilməlidir',
    'booking.loadMore': 'Daha çox',
    'booking.searchProducts': 'Məhsulları axtar...',
    'booking.recommendedProducts': 'Tövsiyə olunan məhsullar',
    'booking.allProducts': 'Bütün məhsullar',
    'booking.selectedProducts': 'Seçilmiş məhsullar',
    'booking.productsTotal': 'Məhsullar cəmi',
    'booking.noProducts': 'Məhsul tapılmadı',
    'booking.orderSummary': 'Sifariş xülasəsi',
    'booking.customerDetails': 'Müştəri məlumatları',
    'booking.appointmentDate': 'Təyinat tarixi',
    'booking.paymentMethod': 'Ödəniş üsulu',
    'booking.total': 'Ümumi',
    'booking.cashPayment': 'Nağd ödəniş',
    'booking.cashPaymentDesc': 'Xidmət zamanı nağd ödəniş',
    'booking.cardPayment': 'Kart ödənişi',
    'booking.cardPaymentDesc': 'Bank kartı ilə ödəniş',
    'booking.posTerminal': 'POS terminal',
    'booking.posTerminalDesc': 'POS terminal vasitəsilə ödəniş',
    'booking.bankTransfer': 'Bank köçürməsi',
    'booking.bankTransferDesc': 'Bank hesabına köçürmə',
    'booking.bankDetails': 'Bank rekvizitləri',
    'booking.bankName': 'Bank adı',
    'booking.accountName': 'Hesab sahibi',
    'booking.accountNumber': 'Hesab nömrəsi',
    'booking.swiftCode': 'SWIFT kodu',
    'booking.confirmBooking': 'Təsdiq et',
    'booking.bookingConfirmed': 'Rezervasiya təsdiqləndi',
    'booking.confirmationMessage': 'Rezervasiyanız uğurla təsdiqləndi. Təsdiq e-poçtu göndərildi.',
    'booking.bookingDate': 'Rezervasiya tarixi',
    'booking.customer': 'Müştəri',
    'booking.contact': 'Əlaqə',
    'booking.totalAmount': 'Ümumi məbləğ',
    'booking.saveBookingDetails': 'Bu məlumatları saxlayın',
    'booking.print': 'Çap et',
    'booking.detailed': 'Ətraflı',
    'booking.backToHome': 'Ana səhifəyə qayıt',
    'booking.error': 'Xəta',
    'booking.errorMessage': 'Rezervasiya zamanı xəta baş verdi',
  },
  en: {
    // Common
    'common.discount': 'DISCOUNT',
    'common.viewDetails': 'View Details',
    'common.viewAll': 'View All',
    'common.search': 'Search...',
    'common.loadMore': 'Load More',
    'common.noData': 'No data found',
    
    // Home
    'home.demoLogin': 'You can login with demo test users',
    'home.viewDetails': 'View Details',
    'home.viewAllProducts': 'View All Products',
    'home.viewAllServices': 'View All Services',
    
    // Services
    'services.title': 'Our Services',
    'services.description': 'Professional beauty services with our expert team',
    'services.search': 'Search services...',
    'services.duration': 'Duration',
    'services.minutes': 'minutes',
    'services.benefits': 'Benefits',
    'services.viewDetails': 'View Details',
    'services.loadMore': 'Load More',
    'services.cta': 'Book Now',
    'services.bookNow': 'Book Now',
    'services.noDescription': 'No description available',
    'services.noServicesAdded': 'No services have been added yet',
    'services.viewServicesPage': 'View Services Page',
    'services.viewAllServices': 'View All Services',
    
    // Service Detail
    'service.backToServices': 'Back to Services',
    'service.minutes': 'minutes',
    'service.benefits': 'Benefits',
    'service.bookNow': 'Book Now',
    'service.recommendedProducts': 'Recommended Products',
    'service.viewProductDetails': 'View Product Details',
    
    // Products
    'products.title': 'Our Products',
    'products.description': 'Quality beauty products',
    'products.search': 'Search products...',
    'products.cta': 'Order Now',
    'products.viewDetails': 'View Details',
    'products.bookNow': 'Order Now',
    'products.noDescription': 'No description available',
    'products.noProductsAdded': 'No products have been added yet',
    'products.viewProductsPage': 'View Products Page',
    
    // Product Detail
    'product.backToProducts': 'Back to Products',
    'product.details': 'Details',
    'product.howToUse': 'How to Use',
    'product.ingredients': 'Ingredients',
    'product.bookAppointment': 'Book Appointment',
    'product.relatedServices': 'Related Services',
    'product.viewServiceDetails': 'View Service Details',
    
    // Contact
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Enter your name',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'Enter your email address',
    'contact.phone': 'Phone',
    'contact.phonePlaceholder': 'Enter your phone number',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'Enter subject',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Enter your message',
    'contact.send': 'Send',
    'contact.address': 'Address',
    'contact.phoneNumber': 'Phone Number',
    'contact.emailAddress': 'Email Address',
    'contact.workingHours': 'Working Hours',
    
    // Booking
    'booking.title': 'Appointment Booking',
    'booking.customerInfo': 'Customer Information',
    'booking.services': 'Services',
    'booking.products': 'Products',
    'booking.payment': 'Payment',
    'booking.confirmation': 'Confirmation',
    'booking.gender': 'Gender',
    'booking.male': 'Male',
    'booking.female': 'Female',
    'booking.fullName': 'Full Name',
    'booking.fullNamePlaceholder': 'e.g. John Smith',
    'booking.fullNameValidation': 'Full name must be between 10-100 characters',
    'booking.genderRequired': 'Gender must be selected',
    'booking.email': 'Email',
    'booking.emailPlaceholder': 'example@example.com',
    'booking.emailValidation': 'Please enter a valid email address',
    'booking.phone': 'Phone',
    'booking.phonePlaceholder': '+1 XXX XXX XXXX',
    'booking.phoneRequired': 'Phone number is required',
    'booking.notes': 'Notes',
    'booking.notesPlaceholder': 'Enter additional notes',
    'booking.date': 'Date',
    'booking.dateRequired': 'Date must be selected',
    'booking.time': 'Time',
    'booking.timeRequired': 'Time must be selected',
    'booking.availableForNextDays': 'Available for next',
    'booking.days': 'days',
    'booking.workingHours': 'Working Hours',
    'booking.next': 'Next',
    'booking.previous': 'Previous',
    'booking.searchServices': 'Search services...',
    'booking.minutes': 'minutes',
    'booking.moreInfo': 'More Info',
    'booking.noDescription': 'No description available',
    'booking.selectStaff': 'Select Staff',
    'booking.chooseStaff': 'Choose Staff',
    'booking.noServices': 'No services found',
    'booking.selectedServices': 'Selected Services',
    'booking.servicesTotal': 'Services Total',
    'booking.totalDuration': 'Total Duration',
    'booking.duration': 'Duration',
    'booking.endTime': 'End Time',
    'booking.servicesRequired': 'At least one service must be selected',
    'booking.staffRequired': 'Staff must be selected for all services',
    'booking.loadMore': 'Load More',
    'booking.searchProducts': 'Search products...',
    'booking.recommendedProducts': 'Recommended Products',
    'booking.allProducts': 'All Products',
    'booking.selectedProducts': 'Selected Products',
    'booking.productsTotal': 'Products Total',
    'booking.noProducts': 'No products found',
    'booking.orderSummary': 'Order Summary',
    'booking.customerDetails': 'Customer Details',
    'booking.appointmentDate': 'Appointment Date',
    'booking.paymentMethod': 'Payment Method',
    'booking.total': 'Total',
    'booking.cashPayment': 'Cash Payment',
    'booking.cashPaymentDesc': 'Pay in cash during service',
    'booking.cardPayment': 'Card Payment',
    'booking.cardPaymentDesc': 'Pay with bank card',
    'booking.posTerminal': 'POS Terminal',
    'booking.posTerminalDesc': 'Pay via POS terminal',
    'booking.bankTransfer': 'Bank Transfer',
    'booking.bankTransferDesc': 'Transfer to bank account',
    'booking.bankDetails': 'Bank Details',
    'booking.bankName': 'Bank Name',
    'booking.accountName': 'Account Holder',
    'booking.accountNumber': 'Account Number',
    'booking.swiftCode': 'SWIFT Code',
    'booking.confirmBooking': 'Confirm',
    'booking.bookingConfirmed': 'Booking Confirmed',
    'booking.confirmationMessage': 'Your booking has been confirmed successfully. Confirmation email sent.',
    'booking.bookingDate': 'Booking Date',
    'booking.customer': 'Customer',
    'booking.contact': 'Contact',
    'booking.totalAmount': 'Total Amount',
    'booking.saveBookingDetails': 'Save these booking details',
    'booking.print': 'Print',
    'booking.detailed': 'Detailed',
    'booking.backToHome': 'Back to Home',
    'booking.error': 'Error',
    'booking.errorMessage': 'An error occurred during booking',
  },
  ru: {
    // Common
    'common.discount': 'СКИДКА',
    'common.viewDetails': 'Подробнее',
    'common.viewAll': 'Смотреть все',
    'common.search': 'Поиск...',
    'common.loadMore': 'Загрузить еще',
    'common.noData': 'Данные не найдены',
    
    // Home
    'home.demoLogin': 'Вы можете войти с демо-пользователями',
    'home.viewDetails': 'Подробнее',
    'home.viewAllProducts': 'Все продукты',
    'home.viewAllServices': 'Все услуги',
    
    // Services
    'services.title': 'Наши услуги',
    'services.description': 'Профессиональные косметические услуги с нашей командой экспертов',
    'services.search': 'Поиск услуг...',
    'services.duration': 'Продолжительность',
    'services.minutes': 'минут',
    'services.benefits': 'Преимущества',
    'services.viewDetails': 'Подробнее',
    'services.loadMore': 'Загрузить еще',
    'services.cta': 'Забронировать',
    'services.bookNow': 'Забронировать',
    'services.noDescription': 'Описание недоступно',
    'services.noServicesAdded': 'Услуги еще не добавлены',
    'services.viewServicesPage': 'Страница услуг',
    'services.viewAllServices': 'Все услуги',
    
    // Service Detail
    'service.backToServices': 'К услугам',
    'service.minutes': 'минут',
    'service.benefits': 'Преимущества',
    'service.bookNow': 'Забронировать',
    'service.recommendedProducts': 'Рекомендуемые продукты',
    'service.viewProductDetails': 'Детали продукта',
    
    // Products
    'products.title': 'Наши продукты',
    'products.description': 'Качественные косметические продукты',
    'products.search': 'Поиск продуктов...',
    'products.cta': 'Заказать',
    'products.viewDetails': 'Подробнее',
    'products.bookNow': 'Заказать',
    'products.noDescription': 'Описание недоступно',
    'products.noProductsAdded': 'Продукты еще не добавлены',
    'products.viewProductsPage': 'Страница продуктов',
    
    // Product Detail
    'product.backToProducts': 'К продуктам',
    'product.details': 'Детали',
    'product.howToUse': 'Как использовать',
    'product.ingredients': 'Состав',
    'product.bookAppointment': 'Записаться',
    'product.relatedServices': 'Связанные услуги',
    'product.viewServiceDetails': 'Детали услуги',
    
    // Contact
    'contact.name': 'Имя',
    'contact.namePlaceholder': 'Введите ваше имя',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'Введите email адрес',
    'contact.phone': 'Телефон',
    'contact.phonePlaceholder': 'Введите номер телефона',
    'contact.subject': 'Тема',
    'contact.subjectPlaceholder': 'Введите тему',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Введите сообщение',
    'contact.send': 'Отправить',
    'contact.address': 'Адрес',
    'contact.phoneNumber': 'Номер телефона',
    'contact.emailAddress': 'Email адрес',
    'contact.workingHours': 'Рабочие часы',
    
    // Booking
    'booking.title': 'Запись на прием',
    'booking.customerInfo': 'Информация о клиенте',
    'booking.services': 'Услуги',
    'booking.products': 'Продукты',
    'booking.payment': 'Оплата',
    'booking.confirmation': 'Подтверждение',
    'booking.gender': 'Пол',
    'booking.male': 'Мужской',
    'booking.female': 'Женский',
    'booking.fullName': 'Полное имя',
    'booking.fullNamePlaceholder': 'например: Иван Петров',
    'booking.fullNameValidation': 'Полное имя должно быть от 10 до 100 символов',
    'booking.genderRequired': 'Необходимо выбрать пол',
    'booking.email': 'Email',
    'booking.emailPlaceholder': 'example@example.com',
    'booking.emailValidation': 'Введите корректный email адрес',
    'booking.phone': 'Телефон',
    'booking.phonePlaceholder': '+7 XXX XXX XX XX',
    'booking.phoneRequired': 'Номер телефона обязателен',
    'booking.notes': 'Заметки',
    'booking.notesPlaceholder': 'Введите дополнительные заметки',
    'booking.date': 'Дата',
    'booking.dateRequired': 'Дата должна быть выбрана',
    'booking.time': 'Время',
    'booking.timeRequired': 'Время должно быть выбрано',
    'booking.availableForNextDays': 'Доступно на следующие',
    'booking.days': 'дней',
    'booking.workingHours': 'Рабочие часы',
    'booking.next': 'Далее',
    'booking.previous': 'Назад',
    'booking.searchServices': 'Поиск услуг...',
    'booking.minutes': 'минут',
    'booking.moreInfo': 'Подробнее',
    'booking.noDescription': 'Описание недоступно',
    'booking.selectStaff': 'Выберите сотрудника',
    'booking.chooseStaff': 'Выберите сотрудника',
    'booking.noServices': 'Услуги не найдены',
    'booking.selectedServices': 'Выбранные услуги',
    'booking.servicesTotal': 'Итого услуги',
    'booking.totalDuration': 'Общая продолжительность',
    'booking.duration': 'Продолжительность',
    'booking.endTime': 'Время окончания',
    'booking.servicesRequired': 'Необходимо выбрать хотя бы одну услугу',
    'booking.staffRequired': 'Необходимо выбрать сотрудника для всех услуг',
    'booking.loadMore': 'Загрузить еще',
    'booking.searchProducts': 'Поиск продуктов...',
    'booking.recommendedProducts': 'Рекомендуемые продукты',
    'booking.allProducts': 'Все продукты',
    'booking.selectedProducts': 'Выбранные продукты',
    'booking.productsTotal': 'Итого продукты',
    'booking.noProducts': 'Продукты не найдены',
    'booking.orderSummary': 'Сводка заказа',
    'booking.customerDetails': 'Данные клиента',
    'booking.appointmentDate': 'Дата приема',
    'booking.paymentMethod': 'Способ оплаты',
    'booking.total': 'Итого',
    'booking.cashPayment': 'Наличными',
    'booking.cashPaymentDesc': 'Оплата наличными при обслуживании',
    'booking.cardPayment': 'Картой',
    'booking.cardPaymentDesc': 'Оплата банковской картой',
    'booking.posTerminal': 'POS терминал',
    'booking.posTerminalDesc': 'Оплата через POS терминал',
    'booking.bankTransfer': 'Банковский перевод',
    'booking.bankTransferDesc': 'Перевод на банковский счет',
    'booking.bankDetails': 'Банковские реквизиты',
    'booking.bankName': 'Название банка',
    'booking.accountName': 'Владелец счета',
    'booking.accountNumber': 'Номер счета',
    'booking.swiftCode': 'SWIFT код',
    'booking.confirmBooking': 'Подтвердить',
    'booking.bookingConfirmed': 'Запись подтверждена',
    'booking.confirmationMessage': 'Ваша запись успешно подтверждена. Письмо с подтверждением отправлено.',
    'booking.bookingDate': 'Дата записи',
    'booking.customer': 'Клиент',
    'booking.contact': 'Контакт',
    'booking.totalAmount': 'Общая сумма',
    'booking.saveBookingDetails': 'Сохраните детали записи',
    'booking.print': 'Печать',
    'booking.detailed': 'Подробно',
    'booking.backToHome': 'На главную',
    'booking.error': 'Ошибка',
    'booking.errorMessage': 'Произошла ошибка при записи',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('az');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['az', 'en', 'ru'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
