
import React, { createContext, useContext, useState, useEffect } from 'react';

// Define available languages
export type Language = 'az' | 'ru' | 'en' | 'uz';

// Define the context type
interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Create the context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Define translations for each language
const translations: Record<Language, Record<string, string>> = {
  az: {
    // Navigation
    'nav.home': 'Ana səhifə',
    'nav.services': 'Xidmətlər',
    'nav.products': 'Məhsullar',
    'nav.about': 'Haqqımızda',
    'nav.contact': 'Əlaqə',
    'nav.bookNow': 'İndi rezervasiya et',
    
    // Common
    'common.loading': 'Yüklənir...',
    'common.error': 'Xəta baş verdi',
    'common.save': 'Yadda saxla',
    'common.cancel': 'Ləğv et',
    'common.submit': 'Təsdiq et',
    'common.view': 'Bax',
    'common.viewAll': 'Hamısına bax',
    'common.status': 'Status',
    'common.date': 'Tarix',
    'common.time': 'Vaxt',
    'common.logout': 'Çıxış',
    'common.logoutSuccess': 'Uğurla çıxış edildi',
    'common.search': 'Axtarış',
    'common.back': 'Geri',
    'common.continue': 'Davam et',
    'common.selected': 'Seçildi',
    'common.discount': 'ENDIRIM',

    // Home
    'home.title': 'Gözəllik salonunuz üçün mükəmməl idarəetmə həlli',
    'home.subtitle': 'Müştərilər, təyinatlar və inventarınızı vahid platformada asanlıqla idarə edin.',
    'home.makeAppointment': 'Təyinat edin',
    'home.viewServices': 'Xidmətlərə baxın',
    'home.platform': 'Bizim platforma üstünlükləri',
    'home.services': 'Xidmətlər',
    'home.products': 'Məhsullar',
    'home.demoText': 'Demo rejimdə test istifadəçiləri ilə giriş edə bilərsiniz',
    'home.viewDetails': 'Ətraflı bax',
    'home.viewAllServices': 'Bütün xidmətlərə bax',
    'home.viewAllProducts': 'Bütün məhsullara bax',
    'home.searchServices': 'Xidmətləri axtar...',

    // Services
    'services.title': 'Xidmətlər',
    'services.description': 'Təbii gözəlliyinizi artırmaq və rifahınızı təşviq etmək üçün hazırlanmış hərtərəfli gözəllik və sağlamlıq xidmətlərimizi kəşf edin.',
    'services.search': 'Xidmətləri axtar...',
    'services.duration': 'Müddət',
    'services.minutes': 'dəq',
    'services.benefits': 'Faydalar',
    'services.viewDetails': 'Ətraflı bax',
    'services.loadMore': 'Daha çox yüklə',
    'services.noResults': 'üçün nəticə tapılmadı',
    'services.cta': 'Premium xidmətlərimizi sınamağa hazırsınız?',
    'services.bookNow': 'Təyinat edin',
    'services.moreBenefits': 'daha çox fayda',
    'services.noDescription': 'Xidmət haqqında məlumat yoxdur',

    // Service Detail
    'service.backToServices': 'Xidmətlərə qayıt',
    'service.benefits': 'Faydalar',
    'service.bookNow': 'İndi rezervasiya et',
    'service.recommendedProducts': 'Tövsiyə olunan məhsullar',
    'service.viewProductDetails': 'Məhsul təfərrüatlarına bax',
    'service.minutes': 'dəqiqə',

    // Products
    'products.title': 'Məhsullar',
    'products.description': 'Gündəlik qulluq və gözəllik rutini üçün premium məhsullarımızı kəşf edin.',
    'products.search': 'Məhsulları axtar...',
    'products.viewDetails': 'Ətraflı bax',
    'products.loadMore': 'Daha çox yüklə',
    'products.noResults': 'üçün nəticə tapılmadı',
    'products.cta': 'Premium məhsullarımızı sınamağa hazırsınız?',
    'products.bookNow': 'Təyinat edin',

    // Product Detail
    'product.backToProducts': 'Məhsullara qayıt',
    'product.details': 'Təfərrüatlar',
    'product.howToUse': 'İstifadə qaydası',
    'product.ingredients': 'Tərkib',
    'product.bookAppointment': 'Təyinat et',
    'product.relatedServices': 'Əlaqəli xidmətlər',
    'product.viewServiceDetails': 'Xidmət təfərrüatlarına bax',

    // Contact
    'contact.name': 'Ad',
    'contact.namePlaceholder': 'Adınızı daxil edin',
    'contact.email': 'E-poçt',
    'contact.emailPlaceholder': 'E-poçt ünvanınızı daxil edin',
    'contact.phone': 'Telefon',
    'contact.phonePlaceholder': 'Telefon nömrənizi daxil edin',
    'contact.subject': 'Mövzu',
    'contact.subjectPlaceholder': 'Mövzunu daxil edin',
    'contact.message': 'Mesaj',
    'contact.messagePlaceholder': 'Mesajınızı daxil edin',
    'contact.send': 'Göndər',
    'contact.address': 'Ünvan',
    'contact.phoneNumber': 'Telefon nömrəsi',
    'contact.emailAddress': 'E-poçt ünvanı',
    'contact.workingHours': 'İş saatları',

    // Booking
    'booking.title': 'Təyinat rezervasiyası',
    'booking.customerInfo': 'Müştəri məlumatı',
    'booking.services': 'Xidmətlər',
    'booking.products': 'Məhsullar',
    'booking.payment': 'Ödəniş',
    'booking.confirmation': 'Təsdiq',
    'booking.total': 'Ümumi',
    'booking.bookingDetails': 'Rezervasiya detalları',
    'booking.name': 'Ad',
    'booking.fullName': 'Tam ad',
    'booking.email': 'E-poçt',
    'booking.phone': 'Telefon',
    'booking.gender': 'Cins',
    'booking.male': 'Kişi',
    'booking.female': 'Qadın',
    'booking.notes': 'Qeydlər',
    'booking.date': 'Tarix',
    'booking.time': 'Vaxt',
    'booking.inTime': 'Giriş vaxtı',
    'booking.outTime': 'Çıxış vaxtı',
    'booking.paymentMethod': 'Ödəniş üsulu',
    'booking.cash': 'Nağd',
    'booking.card': 'Kart',
    'booking.status': 'Status',
    'booking.cancel': 'Sifarişi ləğv et',
    'booking.canceled': 'Sifariş artıq ləğv edilib',
    'booking.successCancel': 'Sifariş uğurla ləğv edildi.',
    'booking.selectService': 'Xidmət seçin',
    'booking.selectStaff': 'İşçi seçin',
    'booking.duration': 'Müddət',
    'booking.minutes': 'dəq',
    'booking.noStaffForService': 'Bu xidmət üçün işçi tapılmadı.',
    'booking.additionalProducts': 'Əlavə məhsullar',
    'booking.selected': 'Seçildi',
    'booking.addItem': 'Əlavə et',
    'booking.selectServiceAndStaff': 'Xahiş edirik xidmət və işçi seçin',
    'booking.availableForNextDays': 'Növbəti',
    'booking.days': 'gün ərzində əlçatandır',
    'booking.workingHours': 'İş saatları',
    'booking.next': 'Növbəti',
    'booking.previous': 'Əvvəlki',
    'booking.searchServices': 'Xidmətləri axtar',
    'booking.searchProducts': 'Məhsulları axtar',
    'booking.moreInfo': 'Ətraflı məlumat',
    'booking.chooseStaff': 'İşçi seçin',
    'booking.servicesTotal': 'Xidmətlər ümumilikdə',
    'booking.productsTotal': 'Məhsullar ümumilikdə',
    'booking.recommendedProducts': 'Tövsiyə olunan məhsullar',
    'booking.allProducts': 'Bütün məhsullar',
    'booking.selectedProducts': 'Seçilmiş məhsullar',
    'booking.orderSummary': 'Sifariş xülasəsi',
    'booking.customerDetails': 'Müştəri məlumatları',
    'booking.appointmentDate': 'Təyinat tarixi',
    'booking.cashPayment': 'Nağd ödəniş',
    'booking.cashPaymentDesc': 'Xidmət yerinə çatdıqda nağd ödəyin',
    'booking.cardPayment': 'Kart ödənişi',
    'booking.cardPaymentDesc': 'Debit və ya kredit kartla ödəyin',
    'booking.posTerminal': 'POS Terminal',
    'booking.posTerminalDesc': 'Yerində POS terminal ilə ödəyin',
    'booking.bankTransfer': 'Bank köçürməsi',
    'booking.bankTransferDesc': 'Bank hesabına köçürmə ilə ödəyin',
    'booking.confirmBooking': 'Rezervasiyanı təsdiq et',

    // Admin
    'admin.dashboard': 'İdarəetmə paneli',
    'admin.customers': 'Müştərilər',
    'admin.services': 'Xidmətlər',
    'admin.products': 'Məhsullar',
    'admin.appointments': 'Təyinatlar',
    'admin.staff': 'İşçilər',
    'admin.settings': 'Tənzimləmələr',
    'admin.login': 'Admin panelə daxil ol',
    'admin.backToSite': 'Sayta qayıt',
    'admin.profile': 'Profil',
    'admin.logout': 'Çıxış',
    'admin.cash': 'Kassa',
    'admin.searchPlaceholder': 'Axtarış...',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.services': 'Услуги',
    'nav.products': 'Продукты',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.bookNow': 'Записаться',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.error': 'Произошла ошибка',
    'common.save': 'Сохранить',
    'common.cancel': 'Отменить',
    'common.submit': 'Подтвердить',
    'common.view': 'Посмотреть',
    'common.viewAll': 'Смотреть все',
    'common.status': 'Статус',
    'common.date': 'Дата',
    'common.time': 'Время',
    'common.logout': 'Выйти',
    'common.logoutSuccess': 'Вы успешно вышли из системы',
    'common.search': 'Поиск',
    'common.back': 'Назад',
    'common.continue': 'Продолжить',
    'common.selected': 'Выбрано',
    'common.discount': 'СКИДКА',

    // Home
    'home.title': 'Идеальное решение для управления вашим салоном красоты',
    'home.subtitle': 'Легко управляйте клиентами, записями и инвентарем на единой платформе.',
    'home.makeAppointment': 'Записаться',
    'home.viewServices': 'Посмотреть услуги',
    'home.platform': 'Преимущества нашей платформы',
    'home.services': 'Услуги',
    'home.products': 'Продукты',
    'home.demoText': 'В демо-режиме вы можете войти с тестовыми пользователями',
    'home.viewDetails': 'Подробнее',
    'home.viewAllServices': 'Все услуги',
    'home.viewAllProducts': 'Все продукты',
    'home.searchServices': 'Поиск услуг...',

    // Services
    'services.title': 'Услуги',
    'services.description': 'Откройте для себя наши комплексные услуги красоты и здоровья, разработанные для улучшения вашей естественной красоты и благополучия.',
    'services.search': 'Поиск услуг...',
    'services.duration': 'Длительность',
    'services.minutes': 'мин',
    'services.benefits': 'Преимущества',
    'services.viewDetails': 'Подробнее',
    'services.loadMore': 'Загрузить еще',
    'services.noResults': 'результатов не найдено для',
    'services.cta': 'Готовы попробовать наши премиум услуги?',
    'services.bookNow': 'Записаться',
    'services.moreBenefits': 'больше преимуществ',
    'services.noDescription': 'Информация об услуге отсутствует',

    // Service Detail
    'service.backToServices': 'Назад к услугам',
    'service.benefits': 'Преимущества',
    'service.bookNow': 'Записаться сейчас',
    'service.recommendedProducts': 'Рекомендуемые продукты',
    'service.viewProductDetails': 'Посмотреть детали продукта',
    'service.minutes': 'минут',

    // Products
    'products.title': 'Продукты',
    'products.description': 'Откройте для себя наши премиальные продукты для ежедневного ухода и красоты.',
    'products.search': 'Поиск продуктов...',
    'products.viewDetails': 'Подробнее',
    'products.loadMore': 'Загрузить еще',
    'products.noResults': 'результатов не найдено для',
    'products.cta': 'Готовы попробовать наши премиум продукты?',
    'products.bookNow': 'Записаться',

    // Product Detail
    'product.backToProducts': 'Назад к продуктам',
    'product.details': 'Детали',
    'product.howToUse': 'Как использовать',
    'product.ingredients': 'Состав',
    'product.bookAppointment': 'Записаться',
    'product.relatedServices': 'Связанные услуги',
    'product.viewServiceDetails': 'Посмотреть детали услуги',

    // Contact
    'contact.name': 'Имя',
    'contact.namePlaceholder': 'Введите ваше имя',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'Введите ваш email',
    'contact.phone': 'Телефон',
    'contact.phonePlaceholder': 'Введите номер телефона',
    'contact.subject': 'Тема',
    'contact.subjectPlaceholder': 'Введите тему',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Введите ваше сообщение',
    'contact.send': 'Отправить',
    'contact.address': 'Адрес',
    'contact.phoneNumber': 'Номер телефона',
    'contact.emailAddress': 'Email адрес',
    'contact.workingHours': 'Рабочие часы',

    // Booking
    'booking.title': 'Запись на прием',
    'booking.customerInfo': 'Информация о клиенте',
    'booking.services': 'Услуги',
    'booking.products': 'Продукты',
    'booking.payment': 'Оплата',
    'booking.confirmation': 'Подтверждение',
    'booking.total': 'Итого',
    'booking.bookingDetails': 'Детали записи',
    'booking.name': 'Имя',
    'booking.fullName': 'Полное имя',
    'booking.email': 'Email',
    'booking.phone': 'Телефон',
    'booking.gender': 'Пол',
    'booking.male': 'Мужской',
    'booking.female': 'Женский',
    'booking.notes': 'Примечания',
    'booking.date': 'Дата',
    'booking.time': 'Время',
    'booking.inTime': 'Время начала',
    'booking.outTime': 'Время окончания',
    'booking.paymentMethod': 'Способ оплаты',
    'booking.cash': 'Наличные',
    'booking.card': 'Карта',
    'booking.status': 'Статус',
    'booking.cancel': 'Отменить заказ',
    'booking.canceled': 'Заказ уже отменен',
    'booking.successCancel': 'Заказ успешно отменен.',
    'booking.selectService': 'Выберите услугу',
    'booking.selectStaff': 'Выберите сотрудника',
    'booking.duration': 'Длительность',
    'booking.minutes': 'мин',
    'booking.noStaffForService': 'Для этой услуги нет доступных сотрудников.',
    'booking.additionalProducts': 'Дополнительные продукты',
    'booking.selected': 'Выбрано',
    'booking.addItem': 'Добавить',
    'booking.selectServiceAndStaff': 'Пожалуйста, выберите услугу и сотрудника',
    'booking.availableForNextDays': 'Доступно в следующие',
    'booking.days': 'дней',
    'booking.workingHours': 'Рабочие часы',
    'booking.next': 'Далее',
    'booking.previous': 'Назад',
    'booking.searchServices': 'Поиск услуг',
    'booking.searchProducts': 'Поиск продуктов',
    'booking.moreInfo': 'Подробнее',
    'booking.chooseStaff': 'Выбрать сотрудника',
    'booking.servicesTotal': 'Итого услуги',
    'booking.productsTotal': 'Итого продукты',
    'booking.recommendedProducts': 'Рекомендуемые продукты',
    'booking.allProducts': 'Все продукты',
    'booking.selectedProducts': 'Выбранные продукты',
    'booking.orderSummary': 'Сводка заказа',
    'booking.customerDetails': 'Данные клиента',
    'booking.appointmentDate': 'Дата записи',
    'booking.cashPayment': 'Оплата наличными',
    'booking.cashPaymentDesc': 'Оплатите наличными при прибытии',
    'booking.cardPayment': 'Оплата картой',
    'booking.cardPaymentDesc': 'Оплатите дебетовой или кредитной картой',
    'booking.posTerminal': 'POS терминал',
    'booking.posTerminalDesc': 'Оплата через POS терминал на месте',
    'booking.bankTransfer': 'Банковский перевод',
    'booking.bankTransferDesc': 'Оплата банковским переводом',
    'booking.confirmBooking': 'Подтвердить бронирование',

    // Admin
    'admin.dashboard': 'Панель управления',
    'admin.customers': 'Клиенты',
    'admin.services': 'Услуги',
    'admin.products': 'Продукты',
    'admin.appointments': 'Записи',
    'admin.staff': 'Персонал',
    'admin.settings': 'Настройки',
    'admin.login': 'Войти в админ панель',
    'admin.backToSite': 'Вернуться на сайт',
    'admin.profile': 'Профиль',
    'admin.logout': 'Выйти',
    'admin.cash': 'Касса',
    'admin.searchPlaceholder': 'Поиск...',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.bookNow': 'Book Now',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.view': 'View',
    'common.viewAll': 'View All',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.logout': 'Logout',
    'common.logoutSuccess': 'Successfully logged out',
    'common.search': 'Search',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.selected': 'Selected',
    'common.discount': 'DISCOUNT',

    // Home
    'home.title': 'Perfect management solution for your beauty salon',
    'home.subtitle': 'Easily manage customers, appointments, and inventory in a single platform.',
    'home.makeAppointment': 'Make Appointment',
    'home.viewServices': 'View Services',
    'home.platform': 'Our Platform Benefits',
    'home.services': 'Services',
    'home.products': 'Products',
    'home.demoText': 'You can log in with test users in demo mode',
    'home.viewDetails': 'View Details',
    'home.viewAllServices': 'View All Services',
    'home.viewAllProducts': 'View All Products',
    'home.searchServices': 'Search services...',

    // Services
    'services.title': 'Services',
    'services.description': 'Discover our comprehensive beauty and wellness services designed to enhance your natural beauty and promote well-being.',
    'services.search': 'Search services...',
    'services.duration': 'Duration',
    'services.minutes': 'min',
    'services.benefits': 'Benefits',
    'services.viewDetails': 'View Details',
    'services.loadMore': 'Load More',
    'services.noResults': 'no results found for',
    'services.cta': 'Ready to try our premium services?',
    'services.bookNow': 'Book Now',
    'services.moreBenefits': 'more benefits',
    'services.noDescription': 'No service information available',

    // Service Detail
    'service.backToServices': 'Back to Services',
    'service.benefits': 'Benefits',
    'service.bookNow': 'Book Now',
    'service.recommendedProducts': 'Recommended Products',
    'service.viewProductDetails': 'View Product Details',
    'service.minutes': 'minutes',

    // Products
    'products.title': 'Products',
    'products.description': 'Discover our premium products for daily care and beauty routine.',
    'products.search': 'Search products...',
    'products.viewDetails': 'View Details',
    'products.loadMore': 'Load More',
    'products.noResults': 'no results found for',
    'products.cta': 'Ready to try our premium products?',
    'products.bookNow': 'Book Now',

    // Product Detail
    'product.backToProducts': 'Back to Products',
    'product.details': 'Details',
    'product.howToUse': 'How to Use',
    'product.ingredients': 'Ingredients',
    'product.bookAppointment': 'Book Appointment',
    'product.relatedServices': 'Related Services',
    'product.viewServiceDetails': 'View Service Details',

    // Contact
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Enter your name',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'Enter your email',
    'contact.phone': 'Phone',
    'contact.phonePlaceholder': 'Enter your phone number',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'Enter subject',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Enter your message',
    'contact.send': 'Send',
    'contact.address': 'Address',
    'contact.phoneNumber': 'Phone Number',
    'contact.emailAddress': 'Email Address',
    'contact.workingHours': 'Working Hours',

    // Booking
    'booking.title': 'Book Your Appointment',
    'booking.customerInfo': 'Customer Info',
    'booking.services': 'Services',
    'booking.products': 'Products',
    'booking.payment': 'Payment',
    'booking.confirmation': 'Confirmation',
    'booking.total': 'Total',
    'booking.bookingDetails': 'Booking Details',
    'booking.name': 'Name',
    'booking.fullName': 'Full Name',
    'booking.email': 'Email',
    'booking.phone': 'Phone',
    'booking.gender': 'Gender',
    'booking.male': 'Male',
    'booking.female': 'Female',
    'booking.notes': 'Notes',
    'booking.date': 'Date',
    'booking.time': 'Time',
    'booking.inTime': 'In time',
    'booking.outTime': 'Out time',
    'booking.paymentMethod': 'Payment Method',
    'booking.cash': 'Cash',
    'booking.card': 'Card',
    'booking.status': 'Status',
    'booking.cancel': 'Cancel Order',
    'booking.canceled': 'Order already canceled',
    'booking.successCancel': 'Order successfully canceled.',
    'booking.selectService': 'Select a Service',
    'booking.selectStaff': 'Select Staff',
    'booking.duration': 'Duration',
    'booking.minutes': 'min',
    'booking.noStaffForService': 'No staff available for this service.',
    'booking.additionalProducts': 'Additional Products',
    'booking.selected': 'Selected',
    'booking.addItem': 'Add item',
    'booking.selectServiceAndStaff': 'Please select a service and staff member',
    'booking.availableForNextDays': 'Available for next',
    'booking.days': 'days',
    'booking.workingHours': 'Working hours',
    'booking.next': 'Next',
    'booking.previous': 'Previous',
    'booking.searchServices': 'Search services',
    'booking.searchProducts': 'Search products',
    'booking.moreInfo': 'More info',
    'booking.chooseStaff': 'Choose staff',
    'booking.servicesTotal': 'Services total',
    'booking.productsTotal': 'Products total',
    'booking.recommendedProducts': 'Recommended products',
    'booking.allProducts': 'All products',
    'booking.selectedProducts': 'Selected products',
    'booking.orderSummary': 'Order summary',
    'booking.customerDetails': 'Customer details',
    'booking.appointmentDate': 'Appointment date',
    'booking.cashPayment': 'Cash Payment',
    'booking.cashPaymentDesc': 'Pay with cash when you arrive',
    'booking.cardPayment': 'Card Payment',
    'booking.cardPaymentDesc': 'Pay with debit or credit card',
    'booking.posTerminal': 'POS Terminal',
    'booking.posTerminalDesc': 'Pay with POS terminal on-site',
    'booking.bankTransfer': 'Bank Transfer',
    'booking.bankTransferDesc': 'Pay via bank account transfer',
    'booking.confirmBooking': 'Confirm Booking',

    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.customers': 'Customers',
    'admin.services': 'Services',
    'admin.products': 'Products',
    'admin.appointments': 'Appointments',
    'admin.staff': 'Staff',
    'admin.settings': 'Settings',
    'admin.login': 'Log in to Admin',
    'admin.backToSite': 'Back to Site',
    'admin.profile': 'Profile',
    'admin.logout': 'Logout',
    'admin.cash': 'Cash',
    'admin.searchPlaceholder': 'Search...',
  },
  uz: {
    // Navigation
    'nav.home': 'Asosiy',
    'nav.services': 'Xizmatlar',
    'nav.products': 'Mahsulotlar',
    'nav.about': 'Biz haqimizda',
    'nav.contact': 'Aloqa',
    'nav.bookNow': 'Hozir band qiling',
    
    // Common
    'common.loading': 'Yuklanmoqda...',
    'common.error': 'Xatolik yuz berdi',
    'common.save': 'Saqlash',
    'common.cancel': 'Bekor qilish',
    'common.submit': 'Tasdiqlash',
    'common.view': 'Ko\'rish',
    'common.viewAll': 'Hammasini ko\'rish',
    'common.status': 'Holat',
    'common.date': 'Sana',
    'common.time': 'Vaqt',
    'common.logout': 'Chiqish',
    'common.logoutSuccess': 'Muvaffaqiyatli chiqildi',
    'common.search': 'Qidirish',
    'common.back': 'Orqaga',
    'common.continue': 'Davom etish',
    'common.selected': 'Tanlandi',
    'common.discount': 'CHEGIRMA',

    // Home
    'home.title': 'Go\'zallik saloningiz uchun mukammal boshqaruv yechimlari',
    'home.subtitle': 'Mijozlar, tayinlangan vaqt va inventarni bir platformada osongina boshqaring.',
    'home.makeAppointment': 'Tayinlash',
    'home.viewServices': 'Xizmatlarni ko\'rish',
    'home.platform': 'Platformamizning afzalliklari',
    'home.services': 'Xizmatlar',
    'home.products': 'Mahsulotlar',
    'home.demoText': 'Demo rejimida test foydalanuvchilari bilan kirishingiz mumkin',
    'home.viewDetails': 'Batafsil',
    'home.viewAllServices': 'Barcha xizmatlar',
    'home.viewAllProducts': 'Barcha mahsulotlar',
    'home.searchServices': 'Xizmatlarni qidirish...',

    // Services
    'services.title': 'Xizmatlar',
    'services.description': 'Tabiiy go\'zalligingizni oshirish va farovonligingizni ta\'minlash uchun mo\'ljallangan keng qamrovli go\'zallik va sog\'liqni saqlash xizmatlarini kashf eting.',
    'services.search': 'Xizmatlarni qidirish...',
    'services.duration': 'Davomiyligi',
    'services.minutes': 'daqiqa',
    'services.benefits': 'Afzalliklar',
    'services.viewDetails': 'Batafsil',
    'services.loadMore': 'Ko\'proq yuklash',
    'services.noResults': 'uchun natija topilmadi',
    'services.cta': 'Premium xizmatlarimizni sinab ko\'rishga tayyormisiz?',
    'services.bookNow': 'Hozir band qiling',
    'services.moreBenefits': 'ko\'proq afzalliklar',
    'services.noDescription': 'Xizmat haqida ma\'lumot yo\'q',

    // Service Detail
    'service.backToServices': 'Xizmatlarga qaytish',
    'service.benefits': 'Afzalliklar',
    'service.bookNow': 'Hozir band qiling',
    'service.recommendedProducts': 'Tavsiya etilgan mahsulotlar',
    'service.viewProductDetails': 'Mahsulot tafsilotlarini ko\'rish',
    'service.minutes': 'daqiqa',

    // Products
    'products.title': 'Mahsulotlar',
    'products.description': 'Kundalik parvarish va go\'zallik tartibingiz uchun premium mahsulotlarimizni kashf eting.',
    'products.search': 'Mahsulotlarni qidirish...',
    'products.viewDetails': 'Batafsil',
    'products.loadMore': 'Ko\'proq yuklash',
    'products.noResults': 'uchun natija topilmadi',
    'products.cta': 'Premium mahsulotlarimizni sinab ko\'rishga tayyormisiz?',
    'products.bookNow': 'Hozir band qiling',

    // Product Detail
    'product.backToProducts': 'Mahsulotlarga qaytish',
    'product.details': 'Tafsilotlar',
    'product.howToUse': 'Qanday ishlatish',
    'product.ingredients': 'Tarkib',
    'product.bookAppointment': 'Tayinlash',
    'product.relatedServices': 'Tegishli xizmatlar',
    'product.viewServiceDetails': 'Xizmat tafsilotlarini ko\'rish',

    // Contact
    'contact.name': 'Ism',
    'contact.namePlaceholder': 'Ismingizni kiriting',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'Email manzilingizni kiriting',
    'contact.phone': 'Telefon',
    'contact.phonePlaceholder': 'Telefon raqamingizni kiriting',
    'contact.subject': 'Mavzu',
    'contact.subjectPlaceholder': 'Mavzuni kiriting',
    'contact.message': 'Xabar',
    'contact.messagePlaceholder': 'Xabaringizni kiriting',
    'contact.send': 'Yuborish',
    'contact.address': 'Manzil',
    'contact.phoneNumber': 'Telefon raqami',
    'contact.emailAddress': 'Email manzili',
    'contact.workingHours': 'Ish vaqtlari',

    // Booking
    'booking.title': 'Tayinlashni band qilish',
    'booking.customerInfo': 'Mijoz ma\'lumotlari',
    'booking.services': 'Xizmatlar',
    'booking.products': 'Mahsulotlar',
    'booking.payment': 'To\'lov',
    'booking.confirmation': 'Tasdiqlash',
    'booking.total': 'Jami',
    'booking.bookingDetails': 'Buyurtma tafsilotlari',
    'booking.name': 'Ism',
    'booking.fullName': 'To\'liq ism',
    'booking.email': 'Email',
    'booking.phone': 'Telefon',
    'booking.gender': 'Jins',
    'booking.male': 'Erkak',
    'booking.female': 'Ayol',
    'booking.notes': 'Izohlar',
    'booking.date': 'Sana',
    'booking.time': 'Vaqt',
    'booking.inTime': 'Kirish vaqti',
    'booking.outTime': 'Chiqish vaqti',
    'booking.paymentMethod': 'To\'lov usuli',
    'booking.cash': 'Naqd pul',
    'booking.card': 'Karta',
    'booking.status': 'Holat',
    'booking.cancel': 'Buyurtmani bekor qilish',
    'booking.canceled': 'Buyurtma allaqachon bekor qilingan',
    'booking.successCancel': 'Buyurtma muvaffaqiyatli bekor qilindi.',
    'booking.selectService': 'Xizmatni tanlang',
    'booking.selectStaff': 'Xodimni tanlang',
    'booking.duration': 'Davomiyligi',
    'booking.minutes': 'daq',
    'booking.noStaffForService': 'Bu xizmat uchun xodim mavjud emas.',
    'booking.additionalProducts': 'Qo\'shimcha mahsulotlar',
    'booking.selected': 'Tanlandi',
    'booking.addItem': 'Qo\'shish',
    'booking.selectServiceAndStaff': 'Iltimos, xizmat va xodimni tanlang',
    'booking.availableForNextDays': 'Keyingi',
    'booking.days': 'kun uchun mavjud',
    'booking.workingHours': 'Ish vaqtlari',
    'booking.next': 'Keyingi',
    'booking.previous': 'Oldingi',
    'booking.searchServices': 'Xizmatlarni qidirish',
    'booking.searchProducts': 'Mahsulotlarni qidirish',
    'booking.moreInfo': 'Batafsil ma\'lumot',
    'booking.chooseStaff': 'Xodimni tanlang',
    'booking.servicesTotal': 'Xizmatlar jami',
    'booking.productsTotal': 'Mahsulotlar jami',
    'booking.recommendedProducts': 'Tavsiya etilgan mahsulotlar',
    'booking.allProducts': 'Barcha mahsulotlar',
    'booking.selectedProducts': 'Tanlangan mahsulotlar',
    'booking.orderSummary': 'Buyurtma xulosasi',
    'booking.customerDetails': 'Mijoz ma\'lumotlari',
    'booking.appointmentDate': 'Tayinlash sanasi',
    'booking.cashPayment': 'Naqd to\'lov',
    'booking.cashPaymentDesc': 'Kelganingizda naqd to\'lang',
    'booking.cardPayment': 'Karta to\'lovi',
    'booking.cardPaymentDesc': 'Debit yoki kredit karta bilan to\'lang',
    'booking.posTerminal': 'POS Terminal',
    'booking.posTerminalDesc': 'Joyida POS terminal bilan to\'lang',
    'booking.bankTransfer': 'Bank o\'tkazmasi',
    'booking.bankTransferDesc': 'Bank hisobi orqali o\'tkazmani amalga oshiring',
    'booking.confirmBooking': 'Bandlashni tasdiqlang',

    // Admin
    'admin.dashboard': 'Boshqaruv paneli',
    'admin.customers': 'Mijozlar',
    'admin.services': 'Xizmatlar',
    'admin.products': 'Mahsulotlar',
    'admin.appointments': 'Tayinlashlar',
    'admin.staff': 'Xodimlar',
    'admin.settings': 'Sozlamalar',
    'admin.login': 'Admin paneliga kirish',
    'admin.backToSite': 'Saytga qaytish',
    'admin.profile': 'Profil',
    'admin.logout': 'Chiqish',
    'admin.cash': 'Kassa',
    'admin.searchPlaceholder': 'Qidirish...',
  }
};

// Create provider component
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Get stored language from localStorage or default to 'az'
  const [language, setLanguage] = useState<Language>(() => {
    const storedLanguage = localStorage.getItem('language') as Language;
    return storedLanguage ? storedLanguage : 'az';
  });

  // Update localStorage when language changes
  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook for using the language context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
