// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euodxcczrhsxcyyecear.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1b2R4Y2N6cmhzeGN5eWVjZWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDU3NTgsImV4cCI6MjA2MjQ4MTc1OH0.MnvdLmsKVUsf_bJzStkS1TiZwBHtZko_stj7eCZ9Sww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);